# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-tools:
    name: Install tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Cache Aftman tools
        uses: actions/cache@v3
        with:
          path: ~/.aftman
          key: aftman-${{ hashFiles('aftman.toml') }}
      - name: Check wally version
        run: wally --version
        
  deploy:
    name: Deploy to wally
    runs-on: ubuntu-latest
    needs: [install-tools]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Restore cached Aftman tools
        uses: actions/cache@v3
        with:
          path: ~/.aftman
          key: aftman-${{ hashFiles('aftman.toml') }}
      - name: Authentificate Wally
        run: wally login --token "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish to wally
        run: wally publish
      
       
      
