# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy:
    name: Deploy to wally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Check wally version
        run: wally --version
        
      - name: Authentificate Wally
        run: wally login --token "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Publish to wally
        run: wally publish --token "${{ secrets.GITHUB_TOKEN }}"
      
       
      
