# when will this work vro

name: Deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  deploy:
    name: Deploy to wally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Check wally version
        run: wally --version
      
  
      - name: Authentificate & Publish to wally
        env:
          GITHUB_TOKEN: ${{ secrets.WALLY_AUTHTOKEN }}
        run: wally publish
      
       
      
